#!/bin/sh

xelatex ElectronicsForEveryone.tex
#xelatex ElectronicsForEveryone.tex
#xelatex ElectronicsForEveryone.tex

gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=Combined.pdf ElectronicsForEveryone.pdf SimplifiedDatasheetsPages.pdf
